version: '3'
services:
  mongo:
    image: mongo
  application:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '80:5000'
    environment:
      - "MONGO_DB_URI=mongodb://mongo:27017/blog"
      - "JWT_SECRET=secret"